### ISSUE TITLE
Default to JupyterLab single document mode (/doc)

### ISSUE THREAD

**Issue by manics** [jupyterhub/repo2docker#1026]
### Proposed change
Switch the default repo2docker interface from jupyter-notebook to JupyterLab's single document mode.

I'd like to gauge everyone's feelings on if/when we'd make the switch.

### Background
The trigger for this comes from the decision to switch Z2JH to JupyterLab: https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/776#issuecomment-797276517. I asked whether we could change Z2JH to not set `singleuser.cmd` and instead default to whatever the default entrypoint/command is in the Docker image and instead change the default in the base docker-stacks images https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/776#issuecomment-804063583, an advantage being we would no longer ignore the default start-up scripts that lead to problems such as https://discourse.jupyter.org/t/pyspark-library-is-missing-from-jupyter-pyspark-notebook-when-running-with-jupyterhub-zero-to-jupyterhub-k8s/8450/2, and also backwards compatibility would hopefully be easier to handle.

@parente pointed me to an existing docker-stacks discussion on switching to JupyterLab https://github.com/jupyter/docker-stacks/issues/1217 where one of the suggestions is to wait for other projects such as Z2JH and BinderHub (i.e. repo2docker) to switch. What does everyone think? If you can envisage switching R2D in the next few months then it might make sense to hold off on the Z2JH switch, and co-ordinate with docker-stacks instead to switch everything in one go. On the other hand if it's longer then we should probably figure out how to switch Z2JH and ensure [older images continue to work](https://github.com/jupyterhub/zero-to-jupyterhub-k8s/issues/776#issuecomment-797276517).

**Comment by SylvainCorlay** [comment]
Thanks! +1000 on this! This is long overdue, as lab is where most of the team has been putting work (and love) for so long. This is also where all the current efforts are going with respect to accessibility, internationalization, collaborative editing, and the 3.x series of lab resolves the main pain points for extension authors.

**Comment by minrk** [comment]
I think we should make this switch now. Summarizing the separate transitions we can make [from discussion in the meeting](https://github.com/jupyterhub/team-compass/blob/master/docs/monthly-meeting/2021-02-18.md#agenda-items) and [pr](https://github.com/jupyterhub/repo2docker/pull/996):

1. default UI to lab in repo2docker (NotebookApp.default_url)
2. default UI (and filepath) to lab in binderhub (URL construction, as in https://github.com/jupyterhub/binderhub/pull/1288)
3. switch server to jupyter_server

Switching UI in repo2docker and binderhub can reasonably be taken at the same time, but technically they are separate as BinderHub has full control over what URLs we redirect to (and with filepath, is fully overridden).

Personally, I think it's appropriate to switch default UI *today*. This can be done entirely on mybinder.org as in https://github.com/jupyterhub/binderhub/pull/1288, or coordinated in both repo2docker and binderhub. The situation with lab and notebook only reverses: this only changes the *default* and is overridden easily with urlpath.

The server switch is a bigger deal, both because it's likely more disruptive (presumably there will be compatibility issues with server extensions - how many server extensions are used on Binder?), and because it's much harder to opt out on Binder (must specify the extreme override `start` command)

**Comment by SylvainCorlay** [comment]
@minrk, item 1 is in PR https://github.com/jupyterhub/repo2docker/pull/1035.

**Comment by manics** [comment]
When people have problems binderising a repo on Discourse we often tell them to try debuggin the problem using repo2docker locally, so if we can keep binder and repo2docker in sync that's one less difference to worry about. It's not essential though.

https://github.com/jupyterhub/binderhub/pull/1288 switches the `filepath` parameter which seems fine to me. For changing the default UI (`/`➡️ `/tree` vs `/`➡️`/lab`) can we do this entirely in the image built by repo2docker, so that custom images such as https://discourse.jupyter.org/t/new-package-to-run-arbitrary-web-service-in-jupyterhub-jhsingle-native-proxy/3493/5 won't be broken by forcing them to `/lab`?

**Comment by betatim** [comment]
I like the idea of trying to take care of this switch within the image built by repo2docker. This could be nicer than https://github.com/jupyterhub/binderhub/pull/1288#issuecomment-817085648.

For a repo that was a built a while ago we told users to use https://mybinder.org/v2/gh/org/repo/HEAD to launch it and that this will start classic notebook. If we change the URL that users are sent to in the container there will be images that used to work but are now broken because they don't have anything serving requests at that new URL. In a way we are changing the default value of a function argument to a value that existing users might not recognise.

How can we transition to the new default without breaking existing links/images?

**Comment by SylvainCorlay** [comment]
> Use https://mybinder.org/v2/gh/org/repo/HEAD to launch it and that this will start classic notebook

We could have a v3...

**Comment by manics** [comment]
It's still not clear to me why BinderHub/mybinder.org should care about whether repo2docker image defaults to jupyterlab or notebook. Can't that be handled entirely within the image built by repo2docker, and mybinder just directs the user to `/` and lets the image take care of whether it goes to lab or notebook? Newly built images would default to jupyterlab, existing images in the cache would remain on notebook.

**Comment by minrk** [comment]
BinderHub doesn't *need* to care, I was mainly pointing out that it *can* make a transition at a different time or in a different way if we want to.

BinderHub does pick the UI for the user in `filepath` in how we construct the url (build `/doc/tree/...` instead of `/tree/...`). That's what https://github.com/jupyterhub/binderhub/pull/1288 does, it doesn't actually change the default when no path is specified.

So I think we should merge both:

- #1035 (default URL is `/doc` making single-document mode the default URL)
- https://github.com/jupyterhub/binderhub/pull/1288 (BinderHub handling filepath URLs consistently with repo2docker default)

**Comment by manics** [comment]
@minrk thanks for the explanation!

**Comment by minrk** [comment]
merged #1035
