### ISSUE TITLE
ci: test suite failing in main branch

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/repo2docker#1198]
There is [a test failure](https://github.com/jupyterhub/repo2docker/actions/runs/3302494726/jobs/5449389423) in the main branch.

`tests/unit/contentproviders/test_git.py` test `test_submodule_clone` fails because its the first to request the fixture [`repo_with_submodule`](https://github.com/jupyterhub/repo2docker/blob/main/tests/conftest.py), which in turn fails to setup.

https://github.com/jupyterhub/repo2docker/blob/e0d5b9bb63a7908b4edd9e6b6d5ca51d47fd9aaf/tests/conftest.py#L124-L157

I'm not sure whats going on yet, help resolving this greatly appreciated as it distracts review of PRs.

![image](https://user-images.githubusercontent.com/3837114/197328329-306f6099-f0d3-4968-8c76-ee8ffd38f8a0.png)

**Comment by consideRatio** [comment]
I think this relates to a new version of `git` in ubuntu: https://bugs.launchpad.net/ubuntu/+source/git/+bug/1993586. The `fatal: transport 'file' not allowed` message led me there.

It is in other words then a breaking change in `git` rather than in repo2docker's Python source code or other Python dependencies.

```
Cloning into '/tmp/tmp0emlwlcs/submod'...
fatal: transport 'file' not allowed
fatal: clone of '/tmp/tmpbvb5bqzk' into submodule path '/tmp/tmp0emlwlcs/submod' failed
```

**Comment by consideRatio** [comment]
Related: https://github.blog/2022-10-18-git-security-vulnerabilities-announced/

**Comment by betatim** [comment]
Unrelated to the CI failure, but related to "can we remove submodule support?": In my opinion submodules are only useful for a very niche set of use-cases, but are used a lot more often than that. They bring a whole host of subtle challenges with them, for users and for repo2docker maintainers. I think we started out with "no submodule support" because of that, but then added it because people who need/want submodules were vocal about it. And I think even with the status quo there are submodule use-cases that don't work properly in repo2docker?!

Maybe this bit of history is useful in deciding what to do about sub-module support in the future.

**Comment by minrk** [comment]
For the most part, I've found that `git clone --recursive` successfully clones any repo, whether it's got submodules or not. I'm not aware of anything not working in repo2docker, and the failure here is only because we set up an unrealistic repo with local-file references in submodules, which is insecure. "Real" submodules should still work fine, I think.

**Comment by betatim** [comment]
My comment about "doesn't work quite right" was more about things like this issue popping up once in a while (yes, they are fake positives because of the testing setup) or people asking for `git submodule update --init --recursive` which IIRC is needed sometimes, maybe?
