### ISSUE TITLE
`--config <my-config-file>` largly ignored as defaults in argparse take precedence

### ISSUE THREAD

**Issue by consideRatio** [jupyterhub/repo2docker#1210]
If `repo2docker --config <my-config-file>` is used, boolean configuration will be ignored.

__Example configuration in `repo2docker_config.json`__

```json
{
  "Repo2Docker": {
    "run": false,
    "push": true
  }
}
```

__Example way to execute repo2docker where the configuration is ignored__

```shell
repo2docker --config=repo2docker_config.json <some repo>
```

## Background

repo2docker has traitlets based configuration and is derived from the traitlets library's Application class. It can be provided both .py and .json file configuration. See [`Application.load_config.file()`](https://traitlets.readthedocs.io/en/stable/config-api.html#traitlets.config.Application.load_config_file) and note that it is used early.

https://github.com/jupyterhub/repo2docker/blob/b6098c02f315a37d690a0c538973de53dd0631a3/repo2docker/__main__.py#L282-L282

The issue is that a config file that provides a boolean value for `Repo2Docker.run` for example will be ignored when the repo2docker CLI is parsing its flags.

https://github.com/jupyterhub/repo2docker/blob/b6098c02f315a37d690a0c538973de53dd0631a3/repo2docker/__main__.py#L329-L330

This could be resolved if there was a way in argparse to check if a flag had been passed or not, or if a default value had been provided. I can imagine an ugly workaround like having a default value of "this-flag-was-not-set" and then check for that or similar, but I'd like to avoid that.

Is there a way to let the traitlets configured defaults be respected instead of beign overruled by the argparse provided defaults?

https://github.com/jupyterhub/repo2docker/blob/b6098c02f315a37d690a0c538973de53dd0631a3/repo2docker/app.py#L326-L332

## Two sets of defaults?

When using the CLI, the defaultof `run` is True (becomes false if `--no-run` is passed), but when using Repo2Docker the application, it will be False by default. If we reconcile these to one default it would become a breaking change, either for the CLI or the library.

## What to do?

I'm looking to make use of the `repo2docker` CLI, but relying on as much as possible to be provided via the provided configuration file. Like that, a repo2docker-service that is supposed to run repo2docker can accept a config file and execute repo2docker based on that config, but if values are ignored by default values, that is a problem.

**Comment by minrk** [comment]
traitlets' own CLI parsing properly handles this, so maybe the argparse CLI should be replaced with the traitlets-standard `Application.launch_instance(argv)` ? Downside: more folks know how to argparse than mess with argparse _via_ traitlets if we want to have finer control over the CLI.

An alternative is to have the default for all argparse values be None (or some Unspecified singleton, if None is a valid value that must be preserved), and only pass args to the App constructor that have been specified.

It will be a bit tricky for argparse to accurately _present_ default values in this case, since the default in argparse is not actually he default value.

Perhaps a custom argparse Action can be used to do nothing other than notice which args have been passed explicitly?

**Comment by consideRatio** [comment]
Thank you for brainstorming with me about this @minrk! I've deliberated quite a bit on your thoughts and the situation

## Make library defaults to match CLI defaults?

We have defaults for the CLI in `__main__.py` and for the library in the Repo2Docker class definition. For example, [`run` is true by default using the CLI](https://github.com/jupyterhub/repo2docker/blob/main/repo2docker/__main__.py#L145-L150), but [false by default using the library](https://github.com/jupyterhub/repo2docker/blob/b6098c02f315a37d690a0c538973de53dd0631a3/repo2docker/app.py#L334-L340).

Would it be acceptable to adjust the library defaults to match the CLI defaults?

- __Yes__: then we can make changes in the CLI parsing to rely on the defaults in the library in some way.
- __No__: then a dedicated way in the CLI to rely on the library defaults instead would be relevant.

## If we say no

If we said no, we could provide a flag or command etc in the CLI to rely on library defaults instead. If so, I was thinking it should only accept [traitlets based flags](https://traitlets.readthedocs.io/en/stable/config.html#command-line-arguments) like `--Repo2Docker.run=True` and a specification of config file(s) to load as it would be a relatively simply implementation.

```python
    # partial CLI code to let repo2docker only care about traitlets args and traitlets config
    r2d = Repo2Docker()
    for config_file in args_config_files:
        r2d.load_config_file(args_config_files)
    r2d.parse_command_line(traitlets_args)
    r2d.initialize()
    r2d.start()
```

A challenge with this is that repo2docker's CLI has positional arguments `repo` and `cmd` (to run in the built container), which makes it weird to provide a subcommand like `repo2docker run-in-traitlets-mode`. Instead one would have to do something like `--cli-parsing-mode=traitlets` where only traitlets flags and `--config` would become accepted.

---

@minrk what do you think about saying yes/no and respective ideas for that?

**Comment by minrk** [comment]
I'm not sure anyone uses repo2docker except via the CLI (our own tests excluded), so I'd call the CLI behavior canonical in any case where they differ. I'm not sure any differences are intentional.

> A challenge with this is that repo2docker's CLI has positional arguments

Positional arguments work fine in traitlets (IPython, jupyter lab, jupyter notebook, nbconvert all use positional args). After parsing, these are available as `.extra_args` ([nbconvert for example](https://github.com/jupyter/nbconvert/blob/326faf14b20e49134eff6e7d0922774a7a8ba4d5/nbconvert/nbconvertapp.py#L387-L392)). _However_, they may be slightly different in that `--` may have to be passed to prevent attempting to parse flags after the first positional arg (I'm not sure, I can never keep track of the details of which CLI parsers stop looking for `--flags` at the first positional arg or not).

> makes it weird to provide a subcommand like repo2docker run-in-traitlets-mode

I wouldn't do that. I think we should have one CLI, and we should pick the implementation that meets our goals (whatever we decide that is).

I do want to say that I don't like forcing every aspect of traitlets on folks, and I think it's absolutely reasonable to write a dedicated CLI for a traitlets-based app, if that's the preference here. Traitlets is a _quick_ way to a CLI (e.g. you get all --Class.trait=value options for free, help, etc.), but it's unlikely to get you the _best_ CLI if you want to design it carefully. But you do have to solve this `cli > config file > default` priority problem. That's only really an issue for the CLI options that have a non-None default _in the cli parser_, because putting the args->r2d behind an `if arg.thing is not None` [like this](https://github.com/jupyterhub/repo2docker/blob/b6098c02f315a37d690a0c538973de53dd0631a3/repo2docker/__main__.py#L383) avoids the issue entirely.

_Another_ option: Because you have a CLI defined outside traitlets, it's _also_ totally valid to have traitlets set by the CLI _not_ have `config=True`. Not every traitlet has to be 'configurable' (i.e. can be loaded from a config file). Since we do have a custom CLI, it's totally valid for `run` to always be an _explicit_ arg (from argparse, default or no), and not valid from a config file. That also solves the priority problem.

---

Aside on what `config=True` means, because not all traitlets must have `config=True`:

- The main thing it means is that the value can be loaded from a config file. Question to answer: does it make sense to override the default behavior in a permanent way via a config file?
- _if_ traitlets CLI parsing is used, it is also exposed on the command-line (this is not relevant if you write your own CLI, like we do in r2d!)

Since r2d uses custom CLI, we _only_ have to consider the config file case for `config=True`, because we can expose non-config traitlets on the CLI no problem. I think this is actually a shortcoming of traitlets CLI - you _can't_ have CLI-only options that aren't also overrideable via config files with a traitlets CLI, but you can with how r2d works today. I think it's valid, in that case, for e.g. `run` to _not_ be a config option. Same for `repo` and `ref` and probably a few others. I think it's appropriate to do a pass on all the traits with config=True in the Repo2Docker class, and check if we really do want them settable from a config file vs just explicit args in the CLI.

**Comment by minrk** [comment]
Looking at our CLI, a reason to remove `config=True` from push/run is that if we fix this priority issue, the current CLI doesn't support overriding the value from config unless it's already the default. We have `--no-run`, but we don't have `--run`, so if you have `run = False` in config, it's actually impossible to run images with repo2docker via the CLI if we fix the priority (the traitlets CLI has a boolean_flag utility to add both explicit true/false options via `--[no-]flag`).

After skimming through what we have, I think we can cover this by having `default=None` on various `action="store_false"` args and friends, and add a few `if args.all_ports is not None` guards, and we should be set.

**Comment by minrk** [comment]
#1211 implements much of this

- use `default=None` to make unspecified values distinguishable from cli default
- remove `config=True` from some options that I think don't make sense in config files, either because the CLI always overrides them, or they don't make sense to persist from one call to the next, or both
