### ISSUE TITLE
Ignored exception *sometimes* at the end of a succesful build

### ISSUE THREAD

**Issue by yuvipanda** [jupyterhub/repo2docker#1379]
Sometimes at the end of a succesful build, I get the following exception:

```
Exception ignored in: <function Application.__del__ at 0x7f31ff7147c0>
Traceback (most recent call last):
  File "/opt/venv/lib/python3.11/site-packages/traitlets/config/application.py", line 1065, in __del__
  File "/opt/venv/lib/python3.11/site-packages/traitlets/config/application.py", line 1054, in close_handlers
  File "/opt/venv/lib/python3.11/site-packages/traitlets/traitlets.py", line 687, in __get__
  File "/opt/venv/lib/python3.11/site-packages/traitlets/traitlets.py", line 666, in get
TypeError: 'NoneType' object is not callabl
```

I don't have a local repro yet, but gonna dig into this a little

**Comment by yuvipanda** [comment]
I could repro it with the following:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock quay.io/jupyterhub/repo2docker:2024.07.0  jupyter-repo2docker --ref=8a6eb6b19ee02f5652a7bb345c200c34155d89df --image=quay.io/veda-binder/staging-jupyterhub-2drepo2docker-e0a968:8a6eb6b19ee02f5652a7bb345c200c34155d89df --no-clean --no-run --json-logs --user-name=jovyan --user-id=1000 https://github.com/jupyterhub/repo2docker
```

**Comment by yuvipanda** [comment]
Minimal reproducer:

```
docker run -v /var/run/docker.sock:/var/run/docker.sock quay.io/jupyterhub/repo2docker:2024.07.0  jupyter-repo2docker --no-run --user-name=jovyan --user-id=1000 --json-logs https://github.com/jupyterhub/repo2docker
```

`--json-logs` is the culprit - removing that makes the error go away

**Comment by yuvipanda** [comment]
On latest `main`, I can repro this with:

```
 jupyter-repo2docker --no-run --user-name=jovyan --user-id=1000 --json-logs https://github.com/jupyterhub/repo2docker
```

Again, removing `--json-logs` makes it go away

**Comment by yuvipanda** [comment]
https://github.com/jupyterhub/repo2docker/blob/8a6eb6b19ee02f5652a7bb345c200c34155d89df/repo2docker/app.py#L548 is the culprit line. If i comment that out, this goes away.

**Comment by yuvipanda** [comment]
Looks like this is a bug introduced between traitlets 5.9 and 5.10! If I run `pip install --force traitlets==5.9.0`, and try to repro it, I can't.

**Comment by yuvipanda** [comment]
https://github.com/ipython/traitlets/pull/818 is the PR that introduced this issue.

**Comment by yuvipanda** [comment]
I tested a later version of python to see if this goes away. it does not :(

**Comment by yuvipanda** [comment]
https://github.com/ipython/traitlets/pull/698 is actually perhaps related, since that seems to have led to https://github.com/ipython/traitlets/issues/722

**Comment by minrk** [comment]
Great job tracking it down! It makes perfect sense that https://github.com/ipython/traitlets/pull/698 would cause this, since `__del__` has to handle objects being partially disassembled if called during process teardown, which people often miss since the situation can ~never happen in tests. Approximately everything (even imported modules!) can be None during `__del__`. The fix is usually: don't do anything you don't _have_ to in `__del__`, and try/except _everything_. I'll try to see what the right fix is in traitlets, it might just be suppressing the error in `__del__`.

If we want/need a workaround here, I believe it would be to call `app.close_handlers()` explicitly before letting it be garbage collected, e.g. in a `finally` [here](https://github.com/jupyterhub/repo2docker/blob/8a6eb6b19ee02f5652a7bb345c200c34155d89df/repo2docker/__main__.py#L485).

**Comment by minrk** [comment]
#1380 is the workaround, plus submitted two PRs upstream that should also fix the underlying issue

**Comment by yuvipanda** [comment]
Excellent work, @minrk! Thank you :)
