### ISSUE TITLE
Sharing Images

### ISSUE THREAD

**Issue by jzf2101** [jupyterhub/repo2docker#339]
We've received feedback on features similar to a push convenience method with repo2docker.  Currently, binderhub is the main tool for sharing images, though you could share those images within JupyterHub as well.  This issue is also related to #37 since one could conceivably be building a shared cloud instance or using someone else's image on a cloud instance. We have some documentation on using repo2docker to build JupyterHub ready images as well.

However, we do not make it clear how best to share images using r2d.  I wanted to open this issue to discuss possible improvements in documentation or features based on this feedback.

**Comment by betatim** [comment]
This is a language lawyer comment: I don't think we should encourage people to share the binary container image that repo2docker produces with others. Mostly because the images we build are a bit weird, and we'd like to reserve the right to make them more or less weird. (Plus the philosophical thing that sharing big binary blobs is so 1990s. People should share the source.)

Comment was mostly triggered by "sharing images", so if we write "reuse image" or "use repo2docker to build images for your JupyterHub" I am already happy.

**Comment by arnim** [comment]
The binder service at GESIS Notebooks[1] currently pushes images to Docker Hub. However, I tend to agree with @betatim on not sharing the binaries itself. 

1) https://notebooks.gesis.org/
2) https://hub.docker.com/u/gesiscss/

**Comment by betatim** [comment]
In the mean time there is also https://github.com/binder-examples/continuous-build/ which shows you how to setup your repo's CI to use repo2docker to build and push your images to a registry like docker hub.

**Comment by manics** [comment]
Closing as there doesn't seem to be anything to do. If you want to discuss further the [Jupyter Community Forum](https://discourse.jupyter.org/) is a great place!
