### ISSUE TITLE
Building consensus around non-standard config files

### ISSUE THREAD

**Issue by betatim** [jupyterhub/repo2docker#386]
At JupyterCon we had multiple discussions with the teams from https://gigantum.com/ and https://codeocean.com/ about standardising/agreeing on improving the compatibility between how environments are specified for repo2docker, gigantum and code ocean.

Two topics that I remember:
* non community standard files like `postBuild`, how can we deal with the fact that there are several names for this?
* repo2docker recognises a special sub-directory called `binder/`. What is a better name that isn't specific to a particular service and low likelihood of already existing in a user's repository?

(if other topics come up I will try and keep this top comment updated with them)

**Comment by dkleissa** [comment]
Thanks @betatim for getting this discussion started! Standardization is hard, especially since we are all _probably_ optimizing for different workflows at the moment and will have conflicting requirements, but I do see a lot that we can agree on. 

One thing to think about is creating a standard for the environment spec "at-rest" so to speak, and possibly have Binder heavily drive/own this. At Gigantum we represent the environment config a certain way to make interactive environment editing and git operations on projects (e.g. branch, merge) work without conflict, and we're still rapidly evolving these components. But something we could certainly provide before the dust has completely settled would be export/import to a standard environment configuration format so a user could take a project and put it on GitHub + Binder or any other service that understands that representation (and likewise easily import a project from some other service).

We're going to think internally a bit, but open to other people's input on which direction we want this discussion to go.

**Comment by dkleissa** [comment]
Maybe “at rest” is the wrong term, more like archival or static (meaning a
representation of the environment at a single point in time), that would be
enough to specify the config for import/export and general compatibility
between tools.

I believe /env is often included in default .gitignore files so probably
not the best choice, but something generic like that is probably a good
idea?

Also agree this doesn’t have to be perfect. For example I do like trying to
stick with standard config files like binder has done, but also don’t see a
big issue with using a few non-standard formats to make sure everything
works as long as we document well.

One thing Gigantum does allow is the user to specify Docker instructions
directly if they want to get under the hood, so ideally we would want to
support that and not have to translate to a bash script or something that
may be a bit brittle.

**Comment by jzf2101** [comment]
I like something like `environment` files may work but i worry if there's a naming collision wiht a type of config file in some language I can't think of

**Comment by willingc** [comment]
@betatim Perhaps `reproducible-snapshot` folder and individual services within that folder `binder`, etc. `archivestamp`,  `buildset`,  `archivebundle`

**Comment by manics** [comment]
It's been a while, and now that we have a [Jupyter community forum](https://discourse.jupyter.org/) I thhink that would be a good place to continue te conversation.
