### ISSUE TITLE
Running setup.py

### ISSUE THREAD

**Issue by psychemedia** [jupyterhub/repo2docker#535]
*[Closing https://github.com/binder-examples/setup.py/issues/2 and moving discussion here.]*

One of the the things I've been wary of when putting in PRs in to package repos to make them runnable in MyBinder to support a "just works" online package demo via MyBinder is adding lots of dependency files at the top level of the repo.

A tidy place to put these files is in the `binder/` directory, but if the `binder/` directory is provided then presumably the `/setup.py` file is *not* run and the package is not installed into the Binder image?

**Comment by betatim** [comment]
Correct. The history of how support for `setup.py` got added is here: https://github.com/jupyter/repo2docker/issues/249

The idea was to opportunistically support packages/repositories while giving control to the maintainers when they want to explicitly support repo2docker. For example by listing their own package in `binder/requirements.txt` to get the released version instead of `master`.

**Comment by psychemedia** [comment]
Okay... so it would be useful if `repo2docker` *could* use the `binder/` environment files and also then run tge package installing setup file? I guess a workaround is a line in `binder/postBuild` to explicitly install the package from the repo?

**Comment by yuvipanda** [comment]
@psychemedia I wonder if adding a `.` to the requirements.txt would be all that is needed.

**Comment by manics** [comment]
Closing as there are workarounds (e.g. postBuild)
