### ISSUE TITLE
document how to choose which registry you want to use

### ISSUE THREAD

**Issue by choldgraf** [jupyterhub/repo2docker#61]

**Comment by willingc** [comment]
@choldgraf Do you want to close this?

**Comment by choldgraf** [comment]
hmmm - I just looked through the docs and didnt see any mention of this. @yuvipanda is it even possible? If not then we should close this, if so then we should document this and then close this :-)

**Comment by yuvipanda** [comment]
I'm unsure what the question means? :)

**Comment by choldgraf** [comment]
r2d will automatically push your image to an image registry...is it possible to configure which registry this goes to? (e.g. gcr.io vs. dockerhub)?

**Comment by yuvipanda** [comment]
IMO that's outside of our scope, since different registries will have wildly varying authentication mechanisms. We function the same way as 'docker push' - so if your image name is 'gcr.io/<something>' it will push there, assuming you have the authentication for that set up. Perhaps we can mention that specifying the image name (and pushing with `--push`) works the same way as `docker push`? So if something works with docker push, it should work with r2d's `--push` (we use the same API). How to get it to work with `docker push` is not something we can help with, but if pushing to your registry works with `docker push` but not `--push` then we can.

**Comment by choldgraf** [comment]
perfect - when I get a moment I'll make a PR adding that language

**Comment by jzf2101** [comment]
Is this still something we need to add?

**Comment by choldgraf** [comment]
hmm, I'm not sure...perhaps we can do a comb-through of repo2docker issues soon to triage / close / etc. Want to spend a moment doing this with me next week @jzf2101 ?
