### ISSUE TITLE
How to Add multiple users inside a container which is built by using repo2docker and How to give sudo access to the user which is used while running repo2docker tool

### ISSUE THREAD

**Issue by mukhendra** [jupyterhub/repo2docker#734]
how to create multiple users on docker container which created by using repo2docker. how to install packages and give sudo access to the users on repo2docker.

**Comment by mukhendra** [comment]
Hi All,
I'm trying to build docker image by using repo2docker tool.
# repo2docker --user-name antony --user-id 1000 https://github.com/sunworshipper/wavedock 
         It's working fine with this command and I'm able to get docker image. 
# docker -dit --name <container name > <imageid>
    To build docker container .
# docker exec -it <container id > /bin/bash.
         By using this i can access docker container with bash prompt.I'm trying to create new users in side the container but i'm getting error " only ROOT user can create users" .
1. Can we create root account inside a docker container while using with repo2docker? if yes please provide me the necessary steps ,if no can you please provide how to get sudo access inside the container which is built by using repo2docker?
2.How to install packages or libraries inside a container without sudo access?

Thanks in advance! quick response should be more grateful.

**Comment by betatim** [comment]
Hi there 👋!

Can we move this discussion to http://discourse.jupyter.org/ (where most of the people who hang out here also hang out, as well as more people). We are trying to streamline the [different discussion places](https://discourse.jupyter.org/t/a-proposal-for-jupyterhub-communications/505) and want to use the issues on GitHub repos for technical discussions on how to change the contents of the repo. More general discussions should go to discourse so that they are easier to find, better indexed by google and generally more accessible than being hidden in the bowls of a GitHub repository ;)

Thanks!
