### ISSUE TITLE
Support for Python dependencies in a form of a wheel file located in repository

### ISSUE THREAD

**Issue by mkhait** [jupyterhub/repo2docker#948]
### Bug description
Straightforward installation of a private Python wheel kept in the repository during docker build does not work, see [topic](https://discourse.jupyter.org/t/local-wheel-file-in-requirements-txt/5768).
As @manics figured, it happens because `requirements.txt` is copied explicitly and used during image build before the rest content arrives.
#### Expected behaviour
local `*.whl` files from repo root should also be copied along with scripts describing dependencies.

#### Actual behaviour
Wheel files are not copied and therefore pip fails to install python requirement specified as a `*.whl` file because it is not found.

### How to reproduce

1. Go to mybinder.com
2. Use https://github.com/dvoskov/DARTS-workshop repository
3. Specify commit `512f3dd06d61fbdacfbb63b2c8fca88238f4e8d2`
4. Hit launch
5. Scroll down
5. See error:

> WARNING: Requirement 'darts-0.1.0-cp37-cp37m-linux_x86_64.whl' looks like a filename, but the file does not exist
> ...
> Processing ./darts-0.1.0-cp37-cp37m-linux_x86_64.whl
> ERROR: Could not install packages due to an EnvironmentError: [Errno 2] No such file or directory: '/home/jovyan/darts-0.1.0-cp37-cp37m-linux_x86_64.whl'

### Your personal set up

No personal setup needed

**Comment by betatim** [comment]
We inspect the `requirements.txt` file to try and figure out if it contains a reference to a local file or not. If it does we first copy the contents of the repository and then install dependencies. This detection doesn't seem to work correctly in your case.

The function that decides if a line in a `requirements.txt` is a local reference or not is https://github.com/jupyterhub/repo2docker/blob/5179447aeac98039ecb3ccc1ae183371a0fb193e/repo2docker/utils.py#L460. This is where I'd start investigating and fixing so that referencing a local wheel file is correctly recognised.

**Comment by mkhait** [comment]
Thanks @betatim!
A combination of '.' and '/' worked out, so the local dependency is correctly processed for the following line:
`./darts-0.1.0-cp37-cp37m-linux_x86_64.whl`

Also, it is t[he official way of including a particular file](https://pip.pypa.io/en/stable/reference/pip_install/#example-requirements-file).

So, my bad in the end :)

**Comment by meeseeksmachine** [comment]
This issue has been mentioned on **Jupyter Community Forum**. There might be relevant details there:

https://discourse.jupyter.org/t/local-wheel-file-in-requirements-txt/5768/5
