### ISSUE TITLE
Automatically repull buildpack-deps

### ISSUE THREAD

**Issue by rkevin-arch** [jupyterhub/repo2docker#953]
### Proposed change
Make repo2docker automatically do a `docker pull buildpack-deps:bionic` when it first starts.

Recently we had issues building an image on a self-hosted binderhub when the image builds perfectly fine locally. The issue turns out to be a 14-month-old `buildpack-deps:bionic` image on the cluster, and repulling the image fixes this issue. Ideally, we should repull the image automatically in repo2docker.

### Alternative options
Repull the image manually. This is fine for personal use (although sometimes users might forget), but is harder to do without manual intervention when running binder on a kubernetes cluster.

### Who would use this feature?
Everyone who wants their image with up-to-date packages.

### How much effort will adding it take?
Probably not too much, since [the Python API already has a pull function](https://docker-py.readthedocs.io/en/stable/images.html?highlight=pull#docker.models.images.ImageCollection.pull). Also we should probably add a CLI option to disable this feature, but that won't take too much effort either.

### Who can do this work?
I can, if people think adding this is a good idea. I'm not sure if there are any downsides to having this feature, so I'll wait for some feedback first.

**Comment by betatim** [comment]
Do you know why the base image changed? repo2docker assumes that rebuilding the same content (at the same revision) will lead to the same image. How true this is in practice depends a bit on how people configure their dependencies and if the base image can change "a lot" then we need to add that to the list of things that can break this promise. I was under the impression though that the base image (once released) would hardly change (in a way that is noticeable to the end user).

Always pulling the image is akin to using the image pull strategy off `Always` for kubernetes pods, which is not considered a  best practice (but popular with many people). Another thing that is hard to do is to decide when to pull the image. repo2docker "starts" every time a new build is triggered in a BinderHub, so on a moderately busy hub that means it starts every few minutes. Pulling the base image each time would make those builds pretty slow and increase bandwidth usage a lot without much benefit because most of the time the image would be the same.

I'd propose a rewording of the alternative: "Add instructions (in BinderHub) to manually remove the base image from the cluster for the cases where you know that the base image has changed in a meaningful way and needs re-pulling." I'd assume it is (very) rare that you have to do this. Maybe you can provide more details about what was broken/why the image needed re-pulling to help understand the situation and context you were in.

**Comment by rkevin-arch** [comment]
After some digging, the issue isn't related to buildpack-deps (it was due to binderhub using an old version of repo2docker by default, and the error message about pip not being able to upgrade some system packages led me to think that the old buildpack-deps was to blame, and I got confused because I was trying multiple things at once) and I'm sorry for assuming that. This issue can be closed if you don't think it's a problem.

From what I can tell, `buildpack-deps` is updated because sometimes the ubuntu packages are updated. It'll be nice to have (since otherwise some apt packages might be not up to date), but doesn't break anything since all the packages are still there.

I still think repulling `buildpack-deps` isn't that big of an problem, since if the image is up-to-date it should take less than a second as Docker figures out `buildpack-deps` is already up to date, but that's just a personal preference.
